version: 1.2.0
services:
  - mysql
  - php:
      version: 7.1

variables:
# Enter your Acquia application variables here.
  global:
    SITENAME: $PIPELINE_CLOUD_SITE
    # The Acquia Cloud application name (aka 'site name').
    # By default, we let Pipelines detect and set this.
    ENVIRONMENT:
    # The Acquia Cloud environment
    # This can be used for code deployment purposes
    DATABASE: $PIPELINE_CLOUD_SITE
    # The Acquia Cloud database name.
    # On Acquia, the database provisioned by default
    # has the sanme name as the application name.
    # Only mnually created databases have unique names,
    # see https://docs.acquia.com/acquia-cloud/manage/database/#adding-a-new-database.

cde-databases:
  - $DATABASE
  #- db2
  # Enter additional databases, if applicable

events:
  build:
    steps:
      - setup:
          type: script
          script:
            - echo "Our global variables:"
            - echo "pipelinecloudsite = $PIPELINE_CLOUD_SITE"
            - echo "sitename = $SITENAME"
            - echo "environment = $ENVIRONMENT"
            - echo "database = $DATABASE"
    # Build a development codebase suitable for testing.
    # Uncomment these lines if you have included testing dependencies in
    # Composer's "require-dev" section.
    #  - build-dev:
    #      type: script
    #      script:
    #        - composer validate --no-check-all --ansi
    #        - composer install
    #
    # Install application.
    # Uncomment these lines if you have tests defined for your application.
    # (Note that you will also need to uncomment the "build-dev" step above so
    # that you have a codebase to work with.) This assumes you have a
    # well-configured settings.php file committed to your repo and all testing
    # dependencies like Behat and PHPUnit as dev
    # dependencies.
    #  - test:
    #      type: script
    #      script:
    #        - drush site-install
    #        - drush runserver --default-server=builtin 8080 &>/dev/null &
    #        - behat
    #        - phpunit
    #
    # Generate artifact. This is the codebase that will be available in the
    # Acquia Cloud interface.
      - build-artifact:
          type: script
          script:
            - composer install --no-dev --optimize-autoloader
  post-deploy:
    steps:
      # Deploy the build artifact to an on-demand environment,
      # and sync the specified databases.
      - deploy:
          script:
            - pipelines-deploy
            - pipelines-sync-dbs $DATABASE
            # See https://docs.acquia.com/acquia-cloud/develop/pipelines/databases/
